import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Popular from '../components/popular'



export default function Home({movies}) {
    console.log(movies.results)
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Popular movies={movies}/>


    </div>
  )
}

export async function getServerSideProps(){
    const request = await fetch (`
https://api.themoviedb.org/3/movie/popular?api_key=9bc6be60644acd7e47721c3e9e7c1d06&language=en-US&page=1`)
    const movies = await request.json()
    return {
        props: {
            movies
        }
    }
}
